### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by eos1d3** [vadrov/stm32g0-display-driver-spi-dma-ili9341-st7789#2]
Hi, thanks a lot for the library. 

I have just tested it with ili9341 without problem. However, I am creating custom fonts using The Dot Factory but I can't get it working.  I have tried almost all options but still failed.

I would like to know how to create fonts for this library. Thank you.

**Comment by vadrov** [comment]
Hi. You can use **PixelFontGeneratorUB**. Please download from my google drive. Link: https://drive.google.com/open?id=105Z92oXuPc31tbzNCNSIot0m41IIiUxG&usp=drive_fs

**Comment by eos1d3** [comment]
Hi, thanks a lot for your help!
